project:
  type: website
  output-dir: _site

website:
  title: "HAR Distributed Framework"

  repo-url: https://github.com/WearNET/HAR-Distributed-Framework
  repo-actions: [source, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: system-overview.qmd
        text: System Overview

    right:
      - icon: github
        text: Repository
        href: https://github.com/WearNET/HAR-Distributed-Framework
        aria-label: GitHub

  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home

      # - section: "1. Framework Overview"
      #   contents:
      #     - href: system-overview.qmd
      #       text: System Overview

      # - section: "2. Hardware Setup"
      #   contents:
      #     - href: hardware-overview.qmd
      #       text: Hardware Overview

      # - section: "3. Software Environment"
      #   contents:
      #     - href: software-overview.qmd
      #       text: Software Overview
      
      - href: expansion-jetson-board.qmd
        text: Expansion on Jetson Boards

      - href: flash-jetson-board.qmd
        text: Flashing Jetson Boards

  page-footer:
    left: |
      HAR Distributed Framework
    right: |
      Technical Documentation & Reproducibility Resources  
      Author: Jhonathan Rivas-Caicedo

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true

execute:
  freeze: auto